### ISSUE TITLE
无法自动回复

### ISSUE THREAD

**Issue by DouBeeTwT** [houko/wechatgpt#1]
链接上我的wechat后可以抓取关键词并通过API返回结果到后台，但是不能在微信中自动回复给群里

**Comment by DouBeeTwT** [comment]
报错信息：
2022/12/11 14:57:12 Ret(1204)
time="2022-12-11T14:57:12+08:00" level=error msg="handle error: Ret(1204)\n"

**Comment by houko** [comment]
这也没说报错位置是哪里呀，debug确认下位置在哪？有新的情报再reopen 这个issue?

**Comment by Kizai** [comment]
我也遇到上面的情况，后台可以看到返回结果，但是没有把信息回传到微信窗口，报错信息也是一样的，log信息中没有代码的运行的行数，无法定位出来，麻烦作者Debug一下，感谢！
![图片](https://user-images.githubusercontent.com/41446543/206991547-ca3f3de6-b9f7-4b44-bced-a72ba87c0b16.png)

**Comment by Kizai** [comment]
我知道了，使用新的微信号就会有这种情况

**Comment by houko** [comment]
<img width="736" alt="image" src="https://user-images.githubusercontent.com/12625278/206997144-b99f3f47-ae76-47cb-8e1c-aa55a6faac4f.png">
那就是号的问题咯

**Comment by Microbion** [comment]
> 我也遇到上面的情况，后台可以看到返回结果，但是没有把信息回传到微信窗口，报错信息也是一样的，log信息中没有代码的运行的行数，无法定位出来，麻烦作者Debug一下，感谢！ ![图片](https://user-images.githubusercontent.com/41446543/206991547-ca3f3de6-b9f7-4b44-bced-a72ba87c0b16.png)

这就很奇怪，我也遇到一样的问题，可是我的号是用了好几年的啊。我是用docker部署到微信的，关键词是呼叫机器人，apikey换成自己的。微信号要什么特征才适用whatgpt呢
![image](https://user-images.githubusercontent.com/35793183/217516665-730d4c37-8466-4d7a-ba86-d2a85955dfc4.png)

**Comment by houko** [comment]
这个得问微信了，调的微信的接口，具体我也搞不清楚
