### ISSUE TITLE
[bug]每次都是这样的报错信息，求解

### ISSUE THREAD

**Issue by sivanWu0222** [houko/wechatgpt#15]
```
time="2022-12-16T22:21:06+08:00" level=info msg="{\n  \"error\": {\n    \"message\": \"This model's maximum context length is 4097 tokens, however you requested 4182 tokens (182 in your prompt; 4000 for the completion). Please reduce your prompt; or completion length.\",\n    \"type\": \"invalid_request_error\",\n    \"param\": null,\n    \"code\": null\n  }\n}\n"
```
经常发送一段文字过去收到报错，其实没有4000token，求解

**Comment by sivanWu0222** [comment]
time="2022-12-16T22:29:42+08:00" level=info msg="{\n  \"error\": {\n    \"message\": \"This model's maximum context length is 4097 tokens, however you requested 4375 tokens (375 in your prompt; 4000 for the completion). Please reduce your prompt; or completion length.\",\n    \"type\": \"invalid_request_error\",\n    \"param\": null,\n    \"code\": null\n  }\n}\n"

**Comment by houko** [comment]
api限制一次回复最多只有400字，超了就会出错
