### ISSUE TITLE
容器运行中出现RetCode：1102就退出了

### ISSUE THREAD

**Issue by MCYUSTC** [houko/wechatgpt#23]
![image](https://user-images.githubusercontent.com/25522073/209333711-2f69a996-57c5-469b-a862-43ce8b99849d.png)
如图所示，然后就挂了
![image](https://user-images.githubusercontent.com/25522073/209333959-69ca536f-5437-48ab-bffc-765348c40cb8.png)

作者大大帮忙看看，感谢

**Comment by houko** [comment]
你启动命令是什么？能发一下吗

**Comment by MCYUSTC** [comment]
> 
最开始启动是：
`docker run -d \
--name wechatgpt \
-e api_key="sk-xxxxxxxxxxxxxxxxxxxxx" \
-e wechat="true" \
-e wechat_keyword="@ChatGPT" \
xiaomoinfo/wechatgpt:latest` 
后面再启动都是docker start/restart container_id了。

**Comment by houko** [comment]
看样子启动命令是没有问题的，可以试试把container删了重新run一下试试
