### ISSUE TITLE
大佬求助，日志里一直显示“没有找到配置文件”

### ISSUE THREAD

**Issue by i-iooi-i** [houko/wechatgpt#24]
![image](https://user-images.githubusercontent.com/1827701/209425296-8aa180a1-daa2-499c-9f24-2190b60f87f4.png)

小白玩家，在启动Docker以后，日志里会提示“找不到配置文件”，没有配置文件，设置了环境变量倒是不影响使用。

只是似乎环境变量里面即便同时设置微信与telegram两个，最后只能使用其中一个对吗？

若是想要使用另外一个的话，是不是要再开一个Docker呢？

**Comment by houko** [comment]
你用docker启动本来就是读环境变量的，正常使用没有影响，源码启动时一般是读配置文件。
你的理解是对的，再开一个docker启动微信就好了。
