### ISSUE TITLE
日志已打印ai回复内容，微信上未推送

### ISSUE THREAD

**Issue by jiaKangZhao** [houko/wechatgpt#26]
一切就绪后，向自己发送了消息，日志已经打印了ai的回复内容，但微信上并未有消息回复，请问造成这个问题的原因是什么

**Comment by houko** [comment]
麻烦发一下具体的操作流程

**Comment by jiaKangZhao** [comment]
目前问题已得到解决，感谢大佬分享！

**Comment by MerriestWly** [comment]
这个的解决方案具体要怎么操作？

**Comment by moemeow233** [comment]
> 目前问题已得到解决，感谢大佬分享！

请问是怎么解决的？
