### ISSUE TITLE
docker命令创建的没有找到配置文件

### ISSUE THREAD

**Issue by In2013** [houko/wechatgpt#28]
`time="2023-01-03T20:06:42Z" level=warning msg="没有找到配置文件，尝试读取环境变量"`

`time="2023-01-04T09:06:10Z" level=fatal msg="wechat network error: Get \"https://login.wx.qq.com/jslogin?_=1672823130103&appid=wx782c26e4c19acffb&fun=new&lang=zh_CN&redirect_uri=https%3A%2F%2Fwx.qq.com%2Fcgi-bin%2Fmmwebwx-bin%2Fwebwxnewloginpage%3Fmod%3Ddesktop\": dial tcp: lookup login.wx.qq.com on 192.168.123.1:53: read udp 172.17.0.2:37207->192.168.123.1:53: i/o timeout"`

**Comment by In2013** [comment]
环境变量设置上了 也没有读取到 然后容器就自动停止

**Comment by houko** [comment]
因为你启动了微信但没有登陆

**Comment by In2013** [comment]
> 因为你启动了微信但没有登陆

不出现二维码哇，不知道问题出在哪，试了交互模式
```
root@DSM:~# docker run -it --name wechatgpt -e api_key="sk-pKHZD1fLYqXDjjsdsdsdUvIODTT3ssjdfadsJC2gTuqqhTum" -e wechat="true" xiaomoinfo/wechatgpt:latest
WARN[0000] 没有找到配置文件，尝试读取环境变量                            
<nil>
FATA[0080] wechat network error: Get "https://login.wx.qq.com/jslogin?_=1672923029541&appid=wx782c26e4c19acffb&fun=new&lang=zh_CN&redirect_uri=https%3A%2F%2Fwx.qq.com%2Fcgi-bin%2Fmmwebwx-bin%2Fwebwxnewloginpage%3Fmod%3Ddesktop": dial tcp: lookup login.wx.qq.com on 223.5.5.5:53: read udp 172.17.0.2:59627->223.5.5.5:53: i/o timeout
```

**Comment by In2013** [comment]
> 因为你启动了微信但没有登陆

不出现二维码哇，不知道问题出在哪，试了交互模式
```
root@DSM:~# docker run -it \
--name wechatgpt \
-e api_key="sk-pKHZD1fLYqXDjjsdsdsdUvIODTT3ssjdfadsJC2gTuqqhTum" \
-e wechat="true" \
xiaomoinfo/wechatgpt:latest

WARN[0000] 没有找到配置文件，尝试读取环境变量                            
<nil>
FATA[0080] wechat network error: Get "https://login.wx.qq.com/jslogin?_=1672923029541&appid=wx782c26e4c19acffb&fun=new&lang=zh_CN&redirect_uri=https%3A%2F%2Fwx.qq.com%2Fcgi-bin%2Fmmwebwx-bin%2Fwebwxnewloginpage%3Fmod%3Ddesktop": dial tcp: lookup login.wx.qq.com on 223.5.5.5:53: read udp 172.17.0.2:59627->223.5.5.5:53: i/o timeout
```

**Comment by In2013** [comment]
> 因为你启动了微信但没有登陆

不出现二维码哇，不知道问题出在哪，试了交互模式

root@DSM:~# docker run -it \
--name wechatgpt \
-e api_key="xxxx" \
-e wechat="true" \
xiaomoinfo/wechatgpt:latest

WARN[0000] 没有找到配置文件，尝试读取环境变量                            
<nil>
FATA[0080] wechat network error: Get "https://login.wx.qq.com/jslogin?_=1672923029541&appid=wx782c26e4c19acffb&fun=new&lang=zh_CN&redirect_uri=https%3A%2F%2Fwx.qq.com%2Fcgi-bin%2Fmmwebwx-bin%2Fwebwxnewloginpage%3Fmod%3Ddesktop": dial tcp: lookup login.wx.qq.com on 223.5.5.5:53: read udp 172.17.0.2:59627->223.5.5.5:53: i/o timeout

**Comment by In2013** [comment]
好了 网络问题，可以扫码了
