### ISSUE TITLE
这个是不是降智版本的ChatGPT 

### ISSUE THREAD

**Issue by i-iooi-i** [houko/wechatgpt#29]
使用了一下，似乎无法关联上下文内容回复~

比如我问：让它做自我介绍，它说自己是来自上海高中学生~
我再问：你在哪里工作？
它回复：它在美国某地做工程师。。。。

因此比较好奇想问下，API调用是不是需要自己做上下文关联呢？ 要不然这天真的聊不下去。😂

**Comment by houko** [comment]
嗯，上下文确实还没做，看另一个issue就知道了。
