### ISSUE TITLE
微信小号容易风控，建议接入UOS，突破网页登陆限制

### ISSUE THREAD

**Issue by hlok666** [houko/wechatgpt#32]
突破网页版限制

顾名思义，PuppetPuppeteer 使用了 Puppeteer，这里使用了微信的网页版。但是我们知道，微信网页版已经被限制使用，当我们扫码登陆成功之后，会显示如下文案：

为了保障你的帐号安全，暂不支持使用网页版微信。你可以前往微信官网 [https://weixin.qq.com/](https://link.zhihu.com/?target=https%3A//weixin.qq.com/) 下载客户端登录。

目前，这个问题是通过开启 uos 协议登录来解决的，具体细节可以阅读 [「免费 UOS 协议快速接入可视化配置面板」](https://link.zhihu.com/?target=https%3A//wechaty.js.org/2022/07/26/free-uos-ui/) 这篇文档。具体到实现上， 通过 Puppeteer 拦截 /cgi-bin/mmwebwx-bin/webwxnewloginpage 请求，并在该请求的 Header 上添加 client-version 和 extspam 两个字段，[具体源码](https://link.zhihu.com/?target=https%3A//github.com/wechaty/puppet-wechat/blob/09fedb147bebee1e28ac03c50debb7267af4b3d9/src/bridge.ts%23L272)如下所示：

const uosHeaders = {
  'client-version' : UOS_PATCH_CLIENT_VERSION,
  extspam : UOS_PATCH_EXTSPAM,
}

page.on('request', (req) => {
  const url = new URL(req.url())
  if (url.pathname === '/cgi-bin/mmwebwx-bin/webwxnewloginpage') {
    const override = {
      headers: {
        ...req.headers(),
        ...uosHeaders,
      },
    }
    this.wrapAsync(req.continue(override))
  }
})

这样，扫码登陆之后便可进入到聊天页面，突破了网页版的限制。使用下面的代码启动 Wechaty 机器人，可以看到效果：

const bot = WechatyBuilder.build({
  name: 'wechat-bot',
  puppetOptions: {
+    head: true, // 关闭无头模式
+    uos: true,  // 开启 uos 协议
  },
  puppet: 'wechaty-puppet-wechat',
})

引自知乎

**Comment by suzukaze-hazuki** [comment]
你可以试试，如果可以的话麻烦提个PR
