### ISSUE TITLE
docker在微信登录后就停止运行

### ISSUE THREAD

**Issue by zuijiasy** [houko/wechatgpt#35]
sudo docker run -it --name wechatgpt -e api_key="*****" -e wechat="true" xiaomoinfo/wechatgpt:latest
WARN[0000] 没有找到配置文件，尝试读取环境变量                            
<nil>
访问下面网址扫描二维码登录
https://login.weixin.qq.com/qrcode/
2023/02/02 04:32:13 扫码成功,请在手机上确认登录

出现以上信息后，docker就自动停止了，也没有提示什么报错，不知道是什么原因，如果微信不登录就不会停

**Comment by smallhyun** [comment]
我也出现这种情况 请问你是怎么解决的
