### ISSUE TITLE
加群微信群后 ，测试，单独触发 关键字才回复问题，无效，一直回复群里的问题。

### ISSUE THREAD

**Issue by wiewiewie** [houko/wechatgpt#37]
加群微信群后 ，测试，单独触发 关键字才回复问题，无效，一直回复群里的问题。

麻烦小莫 抽空检查一下 代码 还是 配置哪个字段的修改 谢谢

**Comment by wiewiewie** [comment]
![image](https://user-images.githubusercontent.com/111113143/216944512-9a22db67-1d68-4784-92d2-87d80a236c0c.png)
root@VM-0-10-ubuntu:/data/wechatgpt/local# cat config.yaml 
chatgpt:
  token: "sk-ZGrt8ODC1RGZbIQLhPW4T3BlbkFJ1jsxABLg8s6NegXXXX"
  wechat: "true"
  wechat_keyword: "细dog"
  #telegram: your telegram token
  #tgWhitelist: username1,username2
  #tgKeyword: chatgpt
这是参数， 像 匹配到 细dog 关键字 在解答问题。

**Comment by ktxptc** [comment]
我也遇到了这个问题，无视关键字设置，别人发的文字不带关键字，也会一直在群里不停回复。。。

**Comment by houko** [comment]
> 我也遇到了这个问题，无视关键字设置，别人发的文字不带关键字，也会一直在群里不停回复。。。

本来预想的都是私聊，当机器人一个智能助手，群组里没有做非常详细的测试。

**Comment by chinesewebman** [comment]
我是2月10号在命令行用go命令运行的，触发词正常。其实，我希望是在群聊里靠触发词来触发，私聊时就不需要触发词。
我看登录成功之后自动拉取了好友名单，需要用这个判断是群聊还是私聊么？我看日志里写的是Recived Group 群名或用户名 Text Msg: ...  好像无法区分群聊和私聊，只能比对那个好友列表？
另：大家试的时候悠着点，我这才试了3天，就被疼讯警告了，只能先停下。过后再找个微信号试吧。
