### ISSUE TITLE
小飞机发消息没回复消息

### ISSUE THREAD

**Issue by cllgeek** [houko/wechatgpt#38]
没有回复消息，体验不了啊

**Comment by houko** [comment]
telegram吗？ 部署流程和启动方式麻烦贴一下？

**Comment by cynic-1** [comment]
> telegram吗？ 部署流程和启动方式麻烦贴一下？

我猜他说的是你贴到README的你创的telegram bot，现在无法使用，如果没有维护的话建议你在README删除。

**Comment by houko** [comment]
> > telegram吗？ 部署流程和启动方式麻烦贴一下？
> 
> 我猜他说的是你贴到README的你创的telegram bot，现在无法使用，如果没有维护的话建议你在README删除。

谢谢解释，了解了，现在用的人太多。openai 的api hard limit上限上
