### ISSUE TITLE
关键字设置没反应

### ISSUE THREAD

**Issue by admin-xpc** [houko/wechatgpt#39]
docker run -d \
--name wechatgpt \
-e wechat="true" \
-e wechat_keyword="小黄" \
xiaomoinfo/wechatgpt:latest

<img width="622" alt="image" src="https://user-images.githubusercontent.com/59109756/217134403-277d6399-2626-49dd-a450-d68a731439e4.png">

**Comment by Microbion** [comment]
docker logs wechatgpt检查一下日志。可能跟我的问题类似
![image](https://user-images.githubusercontent.com/35793183/217517659-f4a86f78-ed44-4ada-9889-609c5c29bb5f.png)

**Comment by houko** [comment]
1204是号的问题
