### ISSUE TITLE
bot回复时，大部分都会带一个? ，有时候不带，请问这是什么情况

### ISSUE THREAD

**Issue by hubeibei** [houko/wechatgpt#42]
<img width="494" alt="image" src="https://user-images.githubusercontent.com/9840974/217452969-dc0d03fe-51f5-4a81-8a1a-d93e3051faaf.png">

**Comment by oishi81** [comment]
我感觉是因为问的问题里没有加“？”
问题带标点问完整了就不会回复时带“？”

另外，有的时候问的问题，反馈是error时（如下），机器人没有响应，似乎可以优化下，做个回复，这样使人明白发生了什么。
time="2023-02-08T05:29:42Z" level=info msg="{\n  \"error\": {\n    \"message\": \"This model's maximum context length is 4097 tokens, however you requested 4451 tokens (451 in your prompt; 4000 for the completion). Please reduce your prompt; or completion length.\",\n    \"type\": \"invalid_request_error\",\n    \"param\": null,\n    \"code\": null\n  }\n}\n"

**Comment by wllmww12** [comment]
返回后的数据编码问题

**Comment by houko** [comment]
> 我感觉是因为问的问题里没有加“？” 问题带标点问完整了就不会回复时带“？”
> 
> 另外，有的时候问的问题，反馈是error时（如下），机器人没有响应，似乎可以优化下，做个回复，这样使人明白发生了什么。 time="2023-02-08T05:29:42Z" level=info msg="{\n "error": {\n "message": "This model's maximum context length is 4097 tokens, however you requested 4451 tokens (451 in your prompt; 4000 for the completion). Please reduce your prompt; or completion length.",\n "type": "invalid_request_error",\n "param": null,\n "code": null\n }\n}\n"

openai有最大返回量的限制，chat.openai.chat的也有最大限制，但是你回复继续的话他就会继续再发。我现在没有加上下文的功能，所以报错就没有回复了。 带问号是因为你给他提的问题没加问号，自动给你补全了，有点多此一举了
