### ISSUE TITLE
使用微信小号（同手机号注册的微信），扫码后无法正常使用

### ISSUE THREAD

**Issue by qwer441505** [houko/wechatgpt#44]
使用微信小号（同手机号注册的微信），扫码后无法正常使用。docker日志没有报错

**Comment by WheaeSong** [comment]
俺也一样！登录成功后程序就异常中断退出
![image](https://user-images.githubusercontent.com/62745793/217727085-6077ab59-bef6-4500-a1d6-b3a1fb9ac173.png)

**Comment by capsshift** [comment]
微信号必须是支付实名认证过的。没认证过。就会中断docker运行。

**Comment by houko** [comment]
这个微信的认证，无解
