### ISSUE TITLE
确定能用吗

### ISSUE THREAD

**Issue by xox-dev** [houko/wechatgpt#47]
level=info msg="{\n  \"error\": {\n    \"message\": \"This model's maximum context length is 2049 tokens, however you requested 4004 tokens (4 in your prompt; 4000 for the completion). Please reduce your prompt; or completion length.\",\n    \"type\": \"invalid_request_error\",\n    \"param\": null,\n    \"code\": null\n  }\n}\n"
time="2023-02-10T07:48:20Z" level=info msg="gpt response text:  \n"

**Comment by fireinrain** [comment]
偶尔会出现 我第一运行 也会出现这个

**Comment by Whalesu** [comment]
curie 或者其他模型的总长度 是2049个token，ChatGPTRequestBody 里 MaxTokens得用模型token上限减去Prompt的字符长度，好像1个token是3/4个字 https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them
