### ISSUE TITLE
使用docker启动，扫码后无法使用

### ISSUE THREAD

**Issue by aeroyu** [houko/wechatgpt#50]
docker run -d \
--name wechatgpt \
-e api_key="你的chatgpt api_key" \
-e wechat="true" \
xiaomoinfo/wechatgpt:latest

启动后，网页扫码
日志返回
2023/02/11 16:54:31 扫码成功,请在手机上确认登录

确认后，容器停止没有任何日志，请问怎么解决

**Comment by kaajii** [comment]
我也是，应该是微信搞的鬼吧

**Comment by houko** [comment]
嗯，启动参数没有问题，大概率是微信做了限制，可以尝试换个号
