### ISSUE TITLE
微信扫码后，docker自动重启。

### ISSUE THREAD

**Issue by Goforfreedom** [houko/wechatgpt#53]
docker环境： 群晖 DSM 7.1
配置：docker run -d \
--name wechatgpt \
-e api_key="xx9" \
-e telegram="xxxQ" \
-e wechat="true" \
xiaomoinfo/wechatgpt:latest

**重现**
重现行为的步骤：
1. 启动docker
2. 复制启动日志中的微信链接，通过chrome浏览器打开链接。
3. 通过手机微信扫描二维码
4. docker重启

telegram可以正常访问docker服务

**预期行为**
正常登录成功

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。
![wechatgptcrash](https://user-images.githubusercontent.com/57245602/218306643-14e52436-5e48-42c0-8c6c-5cd7b849656a.png)

**Comment by houko** [comment]
建议分开部署机器人，一个wecaht，一个telegram

**Comment by Goforfreedom** [comment]
谢谢回复，最初我是单独设置的微信机器人，同样扫描后docker后重启。

涼風羽月 ***@***.***> 于 2023年2月12日周日 21:45写道：

**Comment by houko** [comment]
你单独部署微信的docker 命令和报错信息麻烦贴一下

**Comment by Goforfreedom** [comment]
docker run -d \
--name wechatgpt \
-e api_key="sk-" \
-e wechat="true" \

docker日志里没有报错信息，docker管理器里直接显示重启了
我用的一个新手机号注册的微信，不知是否和这个有关

**Comment by Goforfreedom** [comment]
![wechatgptcrash2](https://user-images.githubusercontent.com/57245602/218317597-9dfab6f6-f50e-4dc3-81f4-4f02e4527706.png)
从群晖系统报错信息来看，docker每五分钟就会因故障重启一次。

**Comment by houko** [comment]
破案了，微信号的问题

**Comment by Goforfreedom** [comment]
谢谢回复，我刚刚翻看了一下closed issue，也猜测是微信号的问题
