### ISSUE TITLE
找不到配置文件

### ISSUE THREAD

**Issue by Wayen495984320** [houko/wechatgpt#55]
**重现**
重现行为的步骤：
![image](https://user-images.githubusercontent.com/58323216/218317150-7b28a380-f428-4d28-bffa-e02fe89591da.jpeg)
**预期行为**
对您预期发生的事情的清晰简洁的描述。

**截图**
![image](https://user-images.githubusercontent.com/58323216/218317088-969a8d6d-c9b9-419b-b142-31581e6daf23.jpe

**Comment by houko** [comment]
> **重现** 重现行为的步骤： ![image](https://user-images.githubusercontent.com/58323216/218317150-7b28a380-f428-4d28-bffa-e02fe89591da.jpeg) **预期行为** 对您预期发生的事情的清晰简洁的描述。
> 
> **截图** ![image](https://user-images.githubusercontent.com/58323216/218317088-969a8d6d-c9b9-419b-b142-31581e6daf23.jpe

大哥，是wecahtgpt不是wechatgtp
