### ISSUE TITLE
docker重启后会自动回复之前提问的所有消息

### ISSUE THREAD

**Issue by LoseRecall** [houko/wechatgpt#58]
1.有时候提问，没有任何响应，去重启服务后，自动回复之前的所有问题。
2.api报错是否可以添加提示

**Comment by houko** [comment]
己有大佬提PR,用新版本就能解决

**Comment by LoseRecall** [comment]
谢谢，不敢用了，微信已经警告了，怕被封号

**Comment by houko** [comment]
> 谢谢，不敢用了，微信已经警告了，怕被封号

大家也悠着点玩，微信没有bot功能，有封号的风险。
