### ISSUE TITLE
chatGPT服务的报错信息也应该显示在聊天窗中，否则用户并不知道为什么失败了

### ISSUE THREAD

**Issue by yongxin-ms** [houko/wechatgpt#59]
**您的功能请求是否与问题相关？请描述。**
目前chatGPT服务器经常会有故障的情况，比如服务器过载，但是程序把出错消息给吃掉了，用户并不知道为什么失败了

**描述您想要的解决方案**
出错的信息也应该显示在聊天窗口中

如果能提供以上功能，我将非常感谢！

**Comment by chinesewebman** [comment]
我也觉得默不作声很难了解发生了什么。但是估计作者选择不输出错误信息是为了避免过早被疼讯发现用了外挂。到服务器看日志呗...

**Comment by yongxin-ms** [comment]
可以先把这个功能加在telegram中嘛

**Comment by auyeungcarl** [comment]
有办法绕过疼讯发现外挂嘛？

**Comment by yongxin-ms** [comment]
我已经把这个问题修复了，提了个PR

**Comment by houko** [comment]
@yongxin-ms 感谢PR,己合并

**Comment by houko** [comment]
> 有办法绕过疼讯发现外挂嘛？

现在监管严了，发不发错误消息 都容易被风控
