### ISSUE TITLE
[need] 限定telegram id使用tgbot

### ISSUE THREAD

**Issue by wyek1n** [houko/wechatgpt#6]
感谢大佬单独分离出telegram，很enjoy！！

能否把限定id的参数也提上日程，大概是这样的，不知道对不对（非专业）：

if (message.user.id == '<USER_ID>') {
 return;
}

PS.用了全github的相关机器人，为啥别的项目都是用无头抓cookie登录，不光麻烦，还老出问题，为啥佬能直接用api，他们都说api用不了，包括star最多的那个项目也这么说，好奇。大佬可以考虑改名？类似telegram-wechat-chatgpt，应该会涨不少star吧。

**Comment by houko** [comment]
谢谢建议，改名的我再考虑一下，我觉得这个名字还不错。
是可以直接用api的，说不能的应该是不会用，事实证明就是可以的。
那个排名第1的涨的有点快，而且我试用了并不好用，所以自己写了一个。

另外关于限定id这个你是打算做什么？有点没太理解，能不能表述的清楚一些。

**Comment by wyek1n** [comment]
> 就不给回

同类.env里面的变量是这样的：

TELEGRAM_ID=123456;789987
TELEGRAM_TOKEN=596935...9NVDLjc8b2I

只有tgid为123456和789987的用户使用该bot，即私人用，不公用。

私聊这个机器人获取账号id：
https://t.me/userinfobot

**Comment by houko** [comment]
@houko 原来是这个意思啊，安排！！

**Comment by houko** [comment]
@wyek1n  搞定，传白名单的用户名就好了，不需要搞这么麻烦还要去查id
https://github.com/houko/wechatgpt/releases/tag/v2.7.0

**Comment by wyek1n** [comment]
> @wyek1n 搞定，传白名单的用户名就好了，不需要搞这么麻烦还要去查id https://github.com/houko/wechatgpt/releases/tag/v2.7.0

telegram有个小技巧，把用户名设置为空项，可以屏蔽大量广告私聊，如果能搞成id的形式可能更科学，或者存在别人为了用我的bot故意换成和bot主一样的username的可能？（黑脸

<img width="516" alt="image" src="https://user-images.githubusercontent.com/96416488/207788729-e1f10d4e-84a4-42c6-bdce-150a306a0b88.png">

**Comment by houko** [comment]
username是唯一的

**Comment by wyek1n** [comment]
> username是唯一的，username和nickname不是一个东西。

嗯嗯，为了拒绝垃圾私聊，我删除了我的username，这种情况，我就不能让bot确定我的唯一性了，白名单也没法限定我了。

**Comment by houko** [comment]
用userid的话，还得自己去查，用户体验太差。

**Comment by houko** [comment]
另外说个题外话，那个star最高的python写的chatgpt项目的作者最近好像阳了，看到发推了。

**Comment by wyek1n** [comment]
> 用userid的话，还得自己去查，用户体验太差。你这个应该算极小众需求

好吧，tg群多了之后，有username真的骚扰不断

**Comment by wyek1n** [comment]
我也有关注大佬宁的推哟

**Comment by houko** [comment]
> > 用userid的话，还得自己去查，用户体验太差。你这个应该算极小众需求
> 
> 好吧，tg群多了之后，有username真的骚扰不断

这个我再想想  实在不行两种都支持也行

**Comment by wyek1n** [comment]
> 

id = 空值 + username

得all in呀

大佬小手一挥就写完
