### ISSUE TITLE
docker运行起来，登陆完成，发送消息，没有回复，后台日志显示调用微信接口出错

### ISSUE THREAD

**Issue by hustyong** [houko/wechatgpt#60]
docker运行起来，登陆完成，发送消息，没有回复，查了后台日志

time="2023-02-13T15:51:21Z" level=info msg="Received Group 尚帝 Text Msg : 小g， 宝宝如何养成早睡早起的习惯"
time="2023-02-13T15:51:21Z" level=info msg="问题： ， 宝宝如何养成早睡早起的习惯"
time="2023-02-13T15:51:21Z" level=info msg="request openai json string : {\"model\":\"text-davinci-003\",\"prompt\":\"， 宝宝如何养成早睡早起的习惯\",\"max_tokens\":4000,\"temperature\":0.7,\"top_p\":1,\"frequency_penalty\":0,\"presence_penalty\":0}"
time="2023-02-13T15:52:02Z" level=info msg="{\"id\":\"cmpl-6jVOsxbTtEvZdqsWNNXIqavVBQCLV\",\"object\":\"text_completion\",\"created\":1676303482,\"model\":\"text-davinci-003\",\"choices\":[{\"text\":\"\\n\\n1. 规定固定的睡眠时间。宝宝每天睡觉的时间要固定，可以按照宝宝的年龄来定（一岁以内的宝宝每天睡11-13个小时，一岁至三岁的宝宝每天睡10-12个小时，三岁以上的宝宝每天睡9-11个小时）。\\n\\n2. 定时定点预备睡觉。每天晚上定时定点，如果宝宝不喜欢睡觉，可以适当放慢睡觉的时间，比如把晚上的活动时间推迟几分钟，让宝宝有充足的时间准备睡觉。\\n\\n3. 建立睡觉前的习惯。建立睡觉前的一些习惯，比如给宝宝洗澡，读故事，唱儿歌等，让宝宝有一个舒服的睡眠环境，有助于宝宝早睡早起。\\n\\n4. 让宝宝在清晨有好的开始。让宝宝在清晨有一个好的开始，可以让宝宝做一些快乐的事情，比如打开窗帘，看阳光，做些活动，开车等。让宝宝体验到清晨的快乐，有助于宝宝早睡早起。\",\"index\":0,\"logprobs\":null,\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":31,\"completion_tokens\":671,\"total_tokens\":702}}\n"
time="2023-02-13T15:52:02Z" level=info msg="gpt response text: \n\n1. 规定固定的睡眠时间。宝宝每天睡觉的时间要固定，可以按照宝宝的年龄来定（一岁以内的宝宝每天睡11-13个小时，一岁至三岁的宝宝每天睡10-12个小时，三岁以上的宝宝每天睡9-11个小时）。\n\n2. 定时定点预备睡觉。每天晚上定时定点，如果宝宝不喜欢睡觉，可以适当放慢睡觉的时间，比如把晚上的活动时间推迟几分钟，让宝宝有充足的时间准备睡觉。\n\n3. 建立睡觉前的习惯。建立睡觉前的一些习惯，比如给宝宝洗澡，读故事，唱儿歌等，让宝宝有一个舒服的睡眠环境，有助于宝宝早睡早起。\n\n4. 让宝宝在清晨有好的开始。让宝宝在清晨有一个好的开始，可以让宝宝做一些快乐的事情，比如打开窗帘，看阳光，做些活动，开车等。让宝宝体验到清晨的快乐，有助于宝宝早睡早起。 \n"
time="2023-02-13T15:52:02Z" level=info msg="Ret(1204)"
time="2023-02-13T15:52:02Z" level=error msg="handle error: Ret(1204)\n"

**Comment by houko** [comment]
号的问题，换号就能解决看以前close的issue能快速解决你的问题。另外提醒微信又在搞妖俄子，别用主号玩机器人
