### ISSUE TITLE
微信给自己发消息，运行日志中能获取回复，但微信不发回复

### ISSUE THREAD

**Issue by KadeFrank** [houko/wechatgpt#68]
Developer您好：

我在群晖上使用您在docker上提供的版本，如下图
![image](https://user-images.githubusercontent.com/125382994/219270657-438af2e7-2d5d-4546-b811-f72b4373ddb8.png)
在使用时，其他用户给我发的消息都可以正常在微信中自动回复
但我自己发消息带关键词时，却无法获取回复
docker日志中的内容多了两句，有error，见下图
![image](https://user-images.githubusercontent.com/125382994/219271024-219392ca-d4e0-4258-8ff8-bcb5a876cf73.png)
别人给我发时没有这两句，请看一下哪里出了问题，谢谢！

**Comment by VPN-V2Ray** [comment]
遇到同样的问题，自己发消息给自己带关键词时，却无法获取chatgpt回复到微信或Telegram，请修复这个问题。谢谢！

**Comment by houko** [comment]
1204错误是微信号的问题
