### ISSUE TITLE
[need] 添加“回话时间”的参数

### ISSUE THREAD

**Issue by wyek1n** [houko/wechatgpt#7]
请求添加类似如下表述的变量：

session_timeout：会话超时时间，默认60秒，单位秒，在会话时间内所有发送给机器人的信息会作为上下文。

目前bot的时间变量好像是0？

<img width="426" alt="image" src="https://user-images.githubusercontent.com/96416488/207849340-e7bd7b78-49d2-4657-9d0d-139eb473c75d.png">

**Comment by irol765** [comment]
大佬，这个在现在的版本内是否已添加？

**Comment by houko** [comment]
> 大佬，这个在现在的版本内是否已添加？

没加，加完了之后会close这个issue的。现在有别的事在忙没空做

**Comment by irol765** [comment]
感谢

**Comment by irol765** [comment]
我找chatgpt改了下代码，说能进行会话保持，大大要试试不。
package openai

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	log "github.com/sirupsen/logrus"
	"github.com/wechatgpt/wechatbot/config"
	"io"
	"io/ioutil"
	"net/http"
	"strings"
)

// ChatGPTResponseBody 请求体
type ChatGPTResponseBody struct {
	ID      string                   `json:"id"`
	Object  string                   `json:"object"`
	Created int                      `json:"created"`
	Model   string                   `json:"model"`
	Choices []map[string]interface{} `json:"choices"`
	Usage   map[string]interface{}   `json:"usage"`
}

// ChatGPTRequestBody 响应体
type ChatGPTRequestBody struct {
	Model            string  `json:"model"`
	Prompt           string  `json:"prompt"`
	MaxTokens        int     `json:"max_tokens"`
	Temperature      float32 `json:"temperature"`
	TopP             int     `json:"top_p"`
	FrequencyPenalty int     `json:"frequency_penalty"`
	PresencePenalty  int     `json:"presence_penalty"`
	ID               string  `json:"id,omitempty"`
}

// Completions https://api.openai.com/v1/completions
func Completions(msg string, id string) (*string, error) {
	apiKey := config.GetOpenAiApiKey()
	if apiKey == nil {
		return nil, errors.New("未配置apiKey")
	}

	requestBody := ChatGPTRequestBody{
		Model:            "text-davinci-003",
		Prompt:           msg,
		MaxTokens:        4000,
		Temperature:      0.7,
		TopP:             1,
		FrequencyPenalty: 0,
		PresencePenalty:  0,
		ID:               id,
	}
	requestData, err := json.Marshal(requestBody)

	if err != nil {
		log.Println(err)
		return nil, err
	}
	log.Printf("request openai json string : %v", string(requestData))
	req, err := http.NewRequest("POST", "https://api.openai.com/v1/completions", bytes.NewBuffer(requestData))
	if err != nil {
		log.Println(err)
		return nil, err
		}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", fmt.Sprintf("Bearer %s", *apiKey))
	client := &http.Client{}
	response, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer func(Body io.ReadCloser) {
		err := Body.Close()
		if err != nil {
			return
		}
	}(response.Body)

	body, err := ioutil.ReadAll(response.Body)
	if err != nil {
		return nil, err
	}

	gptResponseBody := &ChatGPTResponseBody{}
	log.Println(string(body))
	err = json.Unmarshal(body, gptResponseBody)
	if err != nil {
		log.Println(err)
		return nil, err
	}
	var reply string
	if len(gptResponseBody.Choices) > 0 {
		for _, v := range gptResponseBody.Choices {
			reply = v["text"].(string)
			break
		}
	}
	log.Printf("gpt response text: %s \n", reply)
	result := strings.TrimSpace(reply)
	return &result, nil
}

**Comment by houko** [comment]
@irol765 你提PR呀

**Comment by houko** [comment]
#73
