### ISSUE TITLE
【每日重复】微信每晚退出登陆，最后一条 docker 日志显示为：RetCode:1102  Selector:0

### ISSUE THREAD

**Issue by kimyle** [houko/wechatgpt#70]
**重现**
重现行为的步骤：
1. 重启 docker
2. 微信扫码登录
3. 每天凌晨微信都会自动退出登陆
4. 最后一条 docker 日志显示为：RetCode:1102  Selector:0
5. 再次重启后，当天夜里还会继续退出登陆。

**预期行为**
网上搜到有人说，微信会不定期更换登陆 url，继续用老的参数登陆会返回该 ResCode

**服务端 (请填写以下信息):**
- 系统: [树莓派，最新 debian 系统]

**其他描述**
我采用微信小号，一般扫码登录后。手机就处于关机状态。

**Comment by houko** [comment]
重复issue

**Comment by kimyle** [comment]
> 
大佬，这个跟那条重复了，能否提示一下。

**Comment by kimyle** [comment]
> 
大佬，这个跟那条重复了，能否提示一下。

**Comment by houko** [comment]
微信为了安全考虑会做限制和重复认证，这个目前没有别的办法解决。
