### ISSUE TITLE
chatgpt模型的参数 建议改成可变参数

### ISSUE THREAD

**Issue by Lonees-YZH** [houko/wechatgpt#71]
![1676990236628](https://user-images.githubusercontent.com/71118643/220375049-f5ae5ee6-dff0-43f3-ab06-9b29824e6977.jpg)
建议改可变动参数，这样就不会因为请求时间过长而时常报错

**Comment by yongxin-ms** [comment]
请问你这是企业微信么？为什么没被封呢？

**Comment by Lonees-YZH** [comment]
> 

个人微信 暂时还未出现被封号的情况

**Comment by yongxin-ms** [comment]
这么神奇？我用了几分钟就收到警告了，有啥特别的方法么？

**Comment by chinesewebman** [comment]
如果你是企业用途的话，微信官方不是提供了聊天机器人接口么？可以指向自己的服务器，用呗。只是不能群聊，单聊没问题。

**Comment by Lonees-YZH** [comment]
> 这么神奇？我用了几分钟就收到警告了，有啥特别的方法么？

没有其他的方法 可能是参数配置的原因 微信请求的太过频繁会导致封号的可能。

**Comment by Lonees-YZH** [comment]
该issues已通过重新编译打包解决，修改配置参数即可，封号问题暂时未出现。
