### ISSUE TITLE
能不能实现一下便宜的多的 gpt-3.5-turbo，cost 是 text-davinci-003 的十分之一

### ISSUE THREAD

**Issue by kimyle** [houko/wechatgpt#72]
<img width="790" alt="Screenshot 2023-03-03 at 08 50 28" src="https://user-images.githubusercontent.com/4733118/222604021-a3ff1eae-944b-45b1-96a3-36badf89ae52.png">

**Comment by kimyle** [comment]
我自己试了一下，只改 openai 下面 chatgpt.go  里的 Model 不行，报一堆错。

**Comment by houko** [comment]
#73
