### ISSUE TITLE
大佬，一直显示没有配置文件，我不知道哪里挂载错了。

### ISSUE THREAD

**Issue by 281260278** [houko/wechatgpt#74]
我是这么挂载的，应该怎么修改。

**Comment by 281260278** [comment]
图片貌似没显示，
这个是自建目录，docker/wechatgptl/config.yaml，配置文件已经改好了
这个是挂载目录，/wechatgpt/local/config.yaml，我也尝试了/local/config.yaml，貌似也是不行

**Comment by houko** [comment]
docker是读环境变量的
