### ISSUE TITLE
直接调通openai接口的原理是啥，为什么我本地调接口的时候必须翻墙呢

### ISSUE THREAD

**Issue by baijinge0310** [houko/wechatgpt#79]
<img width="529" alt="截屏2023-03-15 09 24 58" src="https://user-images.githubusercontent.com/74445362/225180151-c260fd48-9e0b-4a8f-9727-8b12ac6e9a11.png">
如果把翻墙软件关了，这个请求就会超时，找了一下源码，没看到相关代理的实现，请大佬解惑

**Comment by yongxin-ms** [comment]
这是对方做的限制或者GFW的限制，跟这个源码无关的

**Comment by baijinge0310** [comment]
> 

我知道有限制，但是为什么代码里能直接访问通，而我手动调用接口请求不到呢

**Comment by houko** [comment]
这个我也比较好奇，我不在国内没有这个问题。

**Comment by baijinge0310** [comment]
> 这个我也比较好奇，我不在国内没有这个问题。

我最后一次正常使用是在2月底，今天再用已经用不了了，这是日志
<img width="935" alt="截屏2023-03-15 13 56 47" src="https://user-images.githubusercontent.com/74445362/225220300-dbd4da38-ee40-4b52-965d-d880180fbce1.png">

没开翻墙报timeout,开了翻墙报EOF

**Comment by houko** [comment]
没开： 网络不通不让连
开了： 微信风控不让登
结论： 堵死所有可能性 😢
