### ISSUE TITLE
按照教程启动之后无法收到回信

### ISSUE THREAD

**Issue by sivanWu0222** [houko/wechatgpt#8]
> 背景: 在Telegram机器人中使用chatgpt

按照教程申请了一个Telegram机器人，并执行了如下流程的操作：
1. 配置文件中编写了Telegram的token
2. 配置文件中编写了自己chatgpt的token
3. 配置文件中去掉了`wechat `这行

`go build`之后运行，给自己的Telegram机器人发送信息没有回复，求解

**Comment by houko** [comment]
哈哈，你正好赶上了我在改版。现在主要以docker启动，所以就配置文件那部分还没做，要不你先试试docker启动？

**Comment by houko** [comment]
@sivanWu0222 https://github.com/houko/wechatgpt/releases/tag/v2.9.2
己发布新版本，请更新代码后再次尝试一下

**Comment by sivanWu0222** [comment]
按照教程docker启动后Exit

**Comment by houko** [comment]
@sivanWu0222  麻烦把镜像删除之后重新运行试试

https://github.com/houko/wechatgpt/releases/tag/v2.9.3

**Comment by sivanWu0222** [comment]
拉取源码编译后台运行就ok了
