### ISSUE TITLE
请问你们有没有遇到就是微信扫码授权后。好像过一天就失效了。重启重新授权才行。是chatgpt的限制还是微信的限制啊

### ISSUE THREAD

**Issue by loliconss** [houko/wechatgpt#83]

**Comment by jiangbaobao** [comment]
会一直打印 RetCode:0  Selector:7 ，可以解决一下嘛

**Comment by houko** [comment]
微信需要重新授权

**Comment by loliconss** [comment]
> 微信需要重新授权

后来查知道了。热登录他授权时间随机，后来我改成了免扫码登录。虽然免扫码一次授权时间长了点。但是还是要小号登录。还是麻烦。有时候几天忘登录小号又失效。好像还没有什么有效的方式一直保持授权
