### ISSUE TITLE
支持企业微信嘛

### ISSUE THREAD

**Issue by jiangbaobao** [houko/wechatgpt#86]
**您的功能请求是否与问题相关？请描述。**
清楚简明地描述问题所在。比如，当[...]时我总是很沮丧[...]

**描述您想要的解决方案**
清晰简洁地描述您想要发生的事情。

**描述您考虑过的备选方案**
对您考虑 过的任何替代解决方案或功能的清晰简洁的描述。

**附加上下文**
在此处添加有关功能请求的任何其他上下文或屏幕截图。

**Comment by houko** [comment]
现在不支持噢
