### ISSUE TITLE
 runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MyGodIT** [houko/wechatgpt#9]
linux：Linux 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x72df83]
goroutine 24 [running]:
github.com/wechatgpt/wechatbot/handler/wechat.(*GroupMessageHandler).ReplyText(0xc0000517e0?, 0xc0000ec780)
	/app/handler/wechat/wechat_handler.go:38 +0x123
github.com/wechatgpt/wechatbot/handler/wechat.(*GroupMessageHandler).handle(0x76dd80?, 0xc00006baa0?)
	/app/handler/wechat/wechat_handler.go:22 +0x2a
github.com/wechatgpt/wechatbot/handler/wechat.Handler(0xc0000ec780?)
	/app/handler/wechat/handler.go:27 +0x4e
github.com/eatmoreapple/openwechat.(*Bot).syncCheck(0xc0000f6000)
	/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.2.1/bot.go:288 +0x1d8
github.com/eatmoreapple/openwechat.(*Bot).WebInit.func1()
	/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.2.1/bot.go:240 +0x7d
sync.(*Once).doSlow(0x346f424151414449?, 0x424d4c47494d4f47?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(0x364e56776b784c57?, 0x6249704354714152?)
	/usr/local/go/src/sync/once.go:65 +0x1f
created by github.com/eatmoreapple/openwechat.(*Bot).WebInit
	/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.2.1/bot.go:235 +0x1cd

**Comment by houko** [comment]
请问是以什么方式运行的，参数是什么？

**Comment by MyGodIT** [comment]
> 请问是以什么方式运行的，参数是什么？
docker run -d --name wechatgpt -e apiKey="xxxxxxxxxxx" -e wechat="true" xiaomoinfo/wechatgpt-amd64:latest

**Comment by houko** [comment]
```
docker run -d --name wechatgpt -e api_key="xxxxxxxxxxx" -e wechat="true" xiaomoinfo/wechatgpt:latest
```
麻烦试下这个

**Comment by MyGodIT** [comment]
> ```
> docker run -d --name wechatgpt -e api_key="xxxxxxxxxxx" -e wechat="true" xiaomoinfo/wechatgpt:latest
> ```
> 
> 麻烦试下这个

打印这个日志后，容器直接停掉了，time="2022-12-16T10:05:19Z" level=warning msg="没有找到配置文件，尝试读取环境变量"

**Comment by houko** [comment]
https://github.com/houko/wechatgpt/releases/tag/v2.9.3

麻烦把镜像删掉之后重新运行一下试试

**Comment by MyGodIT** [comment]
> https://github.com/houko/wechatgpt/releases/tag/v2.9.3
> 
> 麻烦把镜像删掉之后重新运行一下试试

time="2022-12-16T10:21:34Z" level=info msg="问题： 发个消息一下"
time="2022-12-16T10:21:34Z" level=info msg="request openai json string : {\"model\":\"text-davinci-003\",\"prompt\":\"发个消息一下\",\"max_tokens\":4000,\"temperature\":0.7,\"top_p\":1,\"frequency_penalty\":0,\"presence_penalty\":0}"
time="2022-12-16T10:21:35Z" level=info msg="{\"id\":\"cmpl-6O28M3SPxkBT6uT55AUftfx615fOk\",\"object\":\"text_completion\",\"created\":1671186094,\"model\":\"text-davinci-003\",\"choices\":[{\"text\":\"\\n\\n你好，最近过得怎么样？\",\"index\":0,\"logprobs\":null,\"finish_reason\":\"stop\"}],\"usage\":{\"prompt_tokens\":13,\"completion_tokens\":26,\"total_tokens\":39}}\n"
time="2022-12-16T10:21:35Z" level=info msg="gpt response text: \n\n你好，最近过得怎么样？ \n"
time="2022-12-16T10:21:35Z" level=info msg="Ret(1204)"
time="2022-12-16T10:21:35Z" level=error msg="handle error: Ret(1204)\n"

**Comment by houko** [comment]
#3
