### ISSUE TITLE
运行成功后发送消息显示连接被拒绝

### ISSUE THREAD

**Issue by MANTOUYAI** [houko/wechatgpt#92]
![image](https://github.com/houko/wechatgpt/assets/136191446/5f40d94b-54a1-4b3f-86de-695232ff831a)
![image](https://github.com/houko/wechatgpt/assets/136191446/56ff6095-9a04-4dad-b0f0-c85be1a054f4)
已经登录成功，运行日志显示收到消息，密钥也是没问题的，请问是哪里出错了？是个人网络问题吗？

**Comment by houko** [comment]
嗯，网络问题

**Comment by MANTOUYAI** [comment]
我是在服务器部署的，请问需要国外服务器吗？

**Comment by houko** [comment]
是的
